### ISSUE TITLE
Crash if isort isn't present

### ISSUE THREAD

**Issue by tleonhardt** [jayrod/cookiecutter-python-cmd2#11]
* Date you used Cookiecutter: Jan 31, 2021
* Cookiecutter version used, if any: 1.7.2
* Python version, if any: 3.9.1
* Operating System: macOS BigSur 11.1

### Description

I was using `cookiecutter` with the `cookiecutter-python-cmd2` template for the first time to create an example application.  Towards the end of asking for questions it crashed with an unhandled exception because I didn't have `isort` installed in the Python environment I was testing it with.  I expected it to not crash.

### What I Did

```
% cookiecutter https://github.com/jayrod/cookiecutter-python-cmd2.git
You've downloaded /Users/toddleonhardt/.cookiecutters/cookiecutter-python-cmd2 before. Is it okay to delete and re-download it? [yes]: yes
... (personal info redacted)
use_pytest [n]: y
create_author_file [y]:
create_banner [y]:
Select open_source_license:
1 - MIT license
2 - BSD license
3 - ISC license
4 - Apache Software License 2.0
5 - GNU General Public License v3
6 - Not open source
Choose from 1, 2, 3, 4, 5, 6 [1]: 1
Traceback (most recent call last):
  File "/var/folders/2z/fyxpg_rs1xz6zq4jvyj3xh080000gn/T/tmpv7gmh_o_.py", line 5, in <module>
    import isort
ModuleNotFoundError: No module named 'isort'
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```

**Comment by jayrod** [comment]
Wow.. you actually did decide to use it 👍  I just realized that I have to update the install instructions.
